---
server:
  host: 0.0.0.0
  service:
    port: {{ server-port }}
  management:
    port: {{ management-port }}

persistence:
  database:
    url: postgres://postgres:password@localhost/{{ artifact_id }}
