[package]
name = "{{ artifact-id }}-api"
version = "0.1.0"
authors = ["{{ author_full }}"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
async-trait = "0.1"
serde = {version = "1.0", features = ["serde_derive"] }
