[workspace]

members = [
    "{{ artifact-id }}-api",
    "{{ artifact-id }}-bin",
    "{{ artifact-id }}-client",
    "{{ artifact-id }}-core",
    "{{ artifact-id }}-persistence",
    "{{ artifact-id }}-server",
    "xtask",
]

default-members = [
    "{{ artifact-id }}-bin",
]
